### ISSUE TITLE
Binary 0.19.0 link

### ISSUE THREAD

**Issue by Jambon1510** [d0ku/GeckoDriver_ARMv6#2]
Hi,
Do I miss something or you did not upload the binary on your project?

**Comment by francescomalandrino** [comment]
It's well hidden ;)

You need to change the branch, and then you will see compiled "geckodriver" binaries.

**Comment by Jambon1510** [comment]
Indeed! Thanks a lot

I have now an other issue running i selenium, I will create a ticket later

**Comment by dezeroku** [comment]
@Jambon1510 Hi, I haven't seen it previosly, sorry... I will probably update README to be more clear. And what about your issues?

**Comment by Jambon1510** [comment]
Thanks  d0ku
Here you go for my issue #3
