### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Noam5** [d0ku/GeckoDriver_ARMv6#4]
I have the following issue when running these 2 lines of code:

from selenium import webdriver
 wser = webdriver.Firefox()

> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
>     keep_alive=True)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
>     self.error_handler.check_response(response)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities

Also, In an older version of selenium (3.3.0) I get the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 155, in __init__
>     keep_alive=True)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
>     response = self.execute(Command.NEW_SESSION, capabilities)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
>     self.error_handler.check_response(response)
>   File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by dezeroku** [comment]
First of all: which version of GeckoDriver are you using, what is your operating system and your ARM device.

**Comment by Noam5** [comment]
I tried with 0.16.1, 0.19.0 and 0.21.0. My operating system is Raspberry pi zero armv6l

**Comment by Noam5** [comment]
I think the first problem is solvable with the parameter  "desired_capabilities".
for example: webdriver.Firefox(desired_capabilities={'?': '?'})

**Comment by dezeroku** [comment]
### Code that worked for me about half a year ago
That's the code which worked for me about half a year ago:
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

caps = DesiredCapabilities().FIREFOX
caps["marionette"] = True
driver = webdriver.Firefox(capabilities=caps, executable_path="./geckodriver")

driver.get("https://accounts.google.com/signin")
```
You have to keep geckodriver binary in the same folder where you run your python file.


### Update your firefox
Also, from what i found, that error can be solved by upgrading your firefox.

### Explicitly provide path to firefox binary
In issue [#3884](https://github.com/SeleniumHQ/selenium/issues/3884) in Selenium issues tracker that problem was solved by directly specyfing firefox path in code. That would look similar to this: 
``` 
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('path_to_firefox')
driver = webdriver.Firefox(firefox_binary=binary)
driver.get('https://google.com')
```
You have to run
```
which firefox
```
 and replace path_to_firefox with output of that command. That program should launch firefox properly and open google.com  

### If above options don't help:
Raspberry pi zero armv6l is NOT an operating system. It is a device on which you run your operating system. Most probably it is Raspbian or something similar. If options above don't help, please try to find name of that OS and version of your Firefox browser.

**Comment by Noam5** [comment]
The firefox explicit path indeed works, although it was horridly slow on the Raspberry pi zero. Still having problem running firefox using the first solution. The operating system I use is Raspbian

**Comment by dezeroku** [comment]
If it works you can use code with providing path explicitly as base for future programs, you just have to start every program with it. Talking about speed... Yeah, it was slow for me too, that's actually why i stopped using it. I don't think there is any workaround for this at the moment, except buying more powerful device. I am glad that it works in the end :)

**Comment by Noam5** [comment]
Thank you so much for your help!
I think i'll move to Raspberry pi B :)

**Comment by dezeroku** [comment]
If you really want to move to something better I would rather consider Raspberry Pi 2B or even something newer. Raspberry Pi B (the first version) has same CPU and amount of memory as RPi Zero, so selenium probably would lag terribly on it too ;) RPi 2B has 4 cores and 1 gig of RAM versus 1 core and 512 mega of ram in RPi Zero/RPi B case, so numbers speak for themselves.
