### ISSUE TITLE
Firefox and selenium versions

### ISSUE THREAD

**Issue by cnrtk** [d0ku/GeckoDriver_ARMv6#5]
Hello,

I am trying to get selenium work on a Raspberry pi zero with latest rasbian stretch lite and branch v.0.18.0, can you please provide a source file for firefox 52.3.0 (esr?) and the right version of selenium? Or it could help to read steps of getting both installed on rasp. pi zero. Thanks.

**Comment by agustinmontero** [comment]
Hi.

I am running a simple test in docker with an image based on Raspbian Jessie. My versions are:

- selenium==3.5.0
- firefox-esr=52.9.0esr-1~deb8u1
- iceweasel=52.9.0esr-1~deb8u1
- geckodrive=0.18.0

Maybe higher versions of selenium work, but I have not tested them.

Regards.

**Comment by cnrtk** [comment]
I was getting some erros with rasbian stretch, I will do a fresh install with jessie and try again. I will let you know.

**Comment by dezeroku** [comment]
Closed due to inactivity.
