### ISSUE TITLE
Download link for geckodriver_ARMv6 0.24

### ISSUE THREAD

**Issue by magnocampos1990** [d0ku/GeckoDriver_ARMv6#6]
Hi,
sorry to bother you.
I can't see the download link of geckodriver0.24 compiled for arm...

can you help me?

**Comment by dezeroku** [comment]
Sure, you have to open branch 0.24.0 and there will be geckodriver file, that you can download.
Or just open this [link](https://github.com/d0ku/GeckoDriver_ARMv6/tree/0.24.0) and you should see geckodriver file.

I should probably publish those binaries as releases, but for now it is as it is.

**Comment by magnocampos1990** [comment]
I'm sorry, my bad... now I can find it...
:D 
many regards, I'll try it on ARMv7... I don't know if it will work

**Comment by dezeroku** [comment]
I believe they should work as ARMv7 is more 'powerful' than v6. Anyway, wish you luck ;)

BTW I have moved all binaries to [Releases tab](https://github.com/d0ku/GeckoDriver_ARMv6/releases), so if you ever have to download different version of binary it should be much easier now. Just click on assets under the version and you should see geckodriver files ready to download.
