### ISSUE TITLE
Can't get a browser running

### ISSUE THREAD

**Issue by demogorgi** [d0ku/GeckoDriver_ARMv6#7]
**Describe the bug**
I cannot get a browser running with GeckoDriver_ARMv6 v21 - v24 with this script
```
from pyvirtualdisplay import Display 
from selenium import webdriver

display = Display(visible=0, size=(800, 600))
display.start()  browser = webdriver.Firefox()

browser.get('http://www.python.org')
browser.close()
```

**Errors**
v21: selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 4
v22-v24: selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

**Expected behavior**
Execution of the script without errors

**Information**
Firefox version: 60.9.0
Selenium version: 3.141.0
Python version: 3.7.3
OS: Raspbian GNU/Linux 10 (buster)
Device: Raspberry Pi Zero w (headless)

**Additional context**
https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html says that my setup should work, doesn't it?

**Comment by dezeroku** [comment]
Hi, are you able to run Firefox at all, e.g. using VNC desktop or with ssh X11Forwarding? It can be quite resource intensive, so it's possible that it just gets killed by process manager, especially if you run it simultaneously with some other software. ~~I also see there are some newer versions of geckodriver, that may help, I will try to compile these.~~ v0.25.0 and v0.26.0 are now available to download, you can try your luck with these.

**Comment by demogorgi** [comment]
> Hi, are you able to run Firefox at all, e.g. using VNC desktop or with ssh X11Forwarding? It can be quite resource intensive,

Hi, good point. Actually not! Firefox crashes and wants to send a bug report to mozilla :-/ So, I guess once I get firefox working (memory consumption seems to be no problem) it will "cooperate" with geckodriver. Anyhow, thanks a lot for your efforts and keep going with GeckoDriver_ARMv6
