### ISSUE TITLE
0.32.0 gecko driver version

### ISSUE THREAD

**Issue by OmarKanj** [d0ku/GeckoDriver_ARMv6#8]
the drivers in the release are outdated for many projects on the raspberry pi, could you please compile a 0.32.0 image for arm v6 since selenium versions 4.0.0 and upwards are not compatible with it?

**Comment by dezeroku** [comment]
Hi, I'll see what I can do during the weekend.

**Comment by dezeroku** [comment]
@OmarKanj could you check if [this release](https://github.com/dezeroku/GeckoDriver_ARMv6/releases/tag/0.32.0) works for you?

**Comment by OmarKanj** [comment]
I have just gotten to test it out, the release works. Do you know where can I find the firefox-esr binary for the arm v6 architecture ?

Thank you btw

**Comment by dezeroku** [comment]
Sure thing!

Your best bet would be to look in the repository of distro you are using. I believe firefox would be more problematic to compile (e.g. you’d need to match the libraries in your system with the ones used during compilation). What distro do you use at the moment?

**Comment by OmarKanj** [comment]
I am using raspberry pi os 32bit. I know its not ubuntu or any other major distro, but it was the only one that worked on my Raspberry pi zero w.

**Comment by dezeroku** [comment]
It should be fine, I think it used to have `firefox-esr`.
Doesn't the usual:
```
apt update
apt install firefox-esr
```
work for you?

**Comment by dezeroku** [comment]
Anyhow, I'll close the issue as the missing geckodriver release is now in place.

Feel free to follow up if you'd like!
